### ISSUE TITLE
wrong example for common_words

### ISSUE THREAD

**Issue by Glyphack** [python-discord/summer-code-jam-2020-qualifier#7]
the part about counting n most common used word in article example is wrong. there is only 2 "the" in that sentence.
```
>>> fairytale.most_common_words(5)
{'the': 3, 'he': 2, 'at': 2, 'all': 2, 'people': 2}
>>> fairytale.most_common_words(3)
{'the': 3, 'he': 2, 'at': 2}
```

**Comment by SebastiaanZ** [comment]
Hello @Glyphack

The sentence contains "the" three times:

> "'But he has nothing at all on!' at last cried out all **the** people. **The** Emperor was vexed, for he knew that **the** people were right."
